#! /bin/bash

function dbuild() {
	docker build -t ecco .
}

function drun() {
	docker run ecco ${@:2}
}

function run() {
    poetry run ecco $@
}

function install() {
    pip install .
}

function lint() {
    poetry run mypy .
}

function format() {
    poetry run black ecco/*
    poetry run flake8 --ignore=E501,W503 $(find ecco -name "*.py")
}

case $1 in 
    dbuild)
        echo "----DBUILD---"
        dbuild
    ;;

    drun)
        echo "-----DRUN----"
        drun
    ;;

    dbuildrun)
        echo "----DBUILD---"
        dbuild
        echo "-----DRUN----"
        drun $@
    ;;

    run)
        echo "-----RUN-----"
        run ${@:2}
    ;;

    install)
        echo "---INSTALL---"
        install
    ;;

    lint)
        echo "----LINT-----"
        lint
    ;;

    format)
        echo "----FORMAT---"
        format
    ;;

    formatlint)
        echo "----FORMAT---"
        format
        echo "----LINT-----"
        lint
    ;;

    all)
        echo "----FORMAT---"
        format
        echo "----LINT-----"
        lint
        echo "-----RUN-----"
        run ${@:2}
    ;;

    *)
        echo "Usage: scripts [dbuild|drun|dbuildrun|run|install|lint|format|formatlint|all] [PASSED ARGUMENTS]"
esac
